apiVersion: v1
kind: Service
metadata:
  name: python-search-app
  namespace: default
spec:
  selector:
    app: python-search-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
  type: NodePort
