apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-search-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-search-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
